import { Metadata } from "next";
import { SITE_URL } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms of Service | JyotishGuru",
  description: "Terms of Service for using the JyotishGuru platform.",
  alternates: {
    canonical: `${SITE_URL}/terms-of-service`,
  },
  openGraph: {
    title: "Terms of Service | JyotishGuru",
    description: "Terms of Service for using the JyotishGuru platform.",
    url: `${SITE_URL}/terms-of-service`,
  },
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="text-center mb-16">
        <h1 className="text-4xl md:text-5xl font-serif font-bold text-[#C9A84C] mb-6">
          Terms of Service
        </h1>
        <div className="w-24 h-1 bg-[#C9A84C]/50 mx-auto rounded-full"></div>
      </div>

      <div className="bg-[#1A1628] border border-[#C9A84C]/20 rounded-2xl p-8 md:p-12 shadow-2xl relative">
        <div className="space-y-8 text-[#E8E4F0]/90 text-lg leading-relaxed">
          <section>
            <h2 className="text-2xl font-serif font-bold text-[#C9A84C] mb-4">1. Acceptance of Terms</h2>
            <p>By accessing and using JyotishGuru, you accept and agree to be bound by the terms and provision of this agreement.</p>
          </section>

          <section>
            <h2 className="text-2xl font-serif font-bold text-[#C9A84C] mb-4">2. Description of Service</h2>
            <p>JyotishGuru provides Vedic Astrology services including Kundali generation, matching, and consultation booking. The guidance provided is based on traditional astrological principles and is for spiritual and personal reflection purposes only.</p>
          </section>

          <section>
            <h2 className="text-2xl font-serif font-bold text-[#C9A84C] mb-4">3. Disclaimer of Liability</h2>
            <p>Astrology is a subjective science. The readings, predictions, and advice provided by Acharya Shri Pankaj Shukla or generated by the platform should not be treated as a substitute for professional medical, legal, financial, or psychological advice. JyotishGuru accepts no liability for actions taken based on consultations or generated reports.</p>
          </section>

          <section>
            <h2 className="text-2xl font-serif font-bold text-[#C9A84C] mb-4">4. User Responsibilities</h2>
            <p>Users are responsible for providing accurate birth details (date, time, and place) as the accuracy of astrological readings depends entirely on this data. You agree not to use the service for any unlawful purpose.</p>
          </section>

          <section>
            <h2 className="text-2xl font-serif font-bold text-[#C9A84C] mb-4">5. Modifications to Service</h2>
            <p>We reserve the right to modify or discontinue, temporarily or permanently, the service (or any part thereof) with or without notice at any time.</p>
          </section>

          <section>
            <h2 className="text-2xl font-serif font-bold text-[#C9A84C] mb-4">6. Contact Information</h2>
            <p>For any questions regarding these Terms, please contact us at contact@jyotishguru.in.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
